/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpeechCheckRouteImport } from './routes/speech-check'
import { Route as SpecialistRouteImport } from './routes/specialist'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as GamesRouteImport } from './routes/games'
import { Route as ExercisesRouteImport } from './routes/exercises'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AddChildRouteImport } from './routes/add-child'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SpecialistIdRouteImport } from './routes/specialist.$id'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as SettingsLanguageRouteImport } from './routes/settings.language'
import { Route as SettingsChildrenRouteImport } from './routes/settings.children'
import { Route as AdminSpecialistsRouteImport } from './routes/admin.specialists'
import { Route as AdminParentsRouteImport } from './routes/admin.parents'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminDiagnosticsRouteImport } from './routes/admin.diagnostics'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminChildrenRouteImport } from './routes/admin.children'
import { Route as AdminAssignmentsRouteImport } from './routes/admin.assignments'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminChildrenIdRouteImport } from './routes/admin.children.$id'

const SpeechCheckRoute = SpeechCheckRouteImport.update({
  id: '/speech-check',
  path: '/speech-check',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialistRoute = SpecialistRouteImport.update({
  id: '/specialist',
  path: '/specialist',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesRoute = ExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AddChildRoute = AddChildRouteImport.update({
  id: '/add-child',
  path: '/add-child',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialistIdRoute = SpecialistIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SpecialistRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsLanguageRoute = SettingsLanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsChildrenRoute = SettingsChildrenRouteImport.update({
  id: '/children',
  path: '/children',
  getParentRoute: () => SettingsRoute,
} as any)
const AdminSpecialistsRoute = AdminSpecialistsRouteImport.update({
  id: '/admin/specialists',
  path: '/admin/specialists',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminParentsRoute = AdminParentsRouteImport.update({
  id: '/admin/parents',
  path: '/admin/parents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDiagnosticsRoute = AdminDiagnosticsRouteImport.update({
  id: '/admin/diagnostics',
  path: '/admin/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/admin/content',
  path: '/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChildrenRoute = AdminChildrenRouteImport.update({
  id: '/admin/children',
  path: '/admin/children',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAssignmentsRoute = AdminAssignmentsRouteImport.update({
  id: '/admin/assignments',
  path: '/admin/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChildrenIdRoute = AdminChildrenIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminChildrenRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-child': typeof AddChildRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/exercises': typeof ExercisesRoute
  '/games': typeof GamesRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRouteWithChildren
  '/specialist': typeof SpecialistRouteWithChildren
  '/speech-check': typeof SpeechCheckRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/assignments': typeof AdminAssignmentsRoute
  '/admin/children': typeof AdminChildrenRouteWithChildren
  '/admin/content': typeof AdminContentRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/diagnostics': typeof AdminDiagnosticsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/parents': typeof AdminParentsRoute
  '/admin/specialists': typeof AdminSpecialistsRoute
  '/settings/children': typeof SettingsChildrenRoute
  '/settings/language': typeof SettingsLanguageRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/specialist/$id': typeof SpecialistIdRoute
  '/admin/': typeof AdminIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/admin/children/$id': typeof AdminChildrenIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-child': typeof AddChildRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/exercises': typeof ExercisesRoute
  '/games': typeof GamesRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/progress': typeof ProgressRoute
  '/specialist': typeof SpecialistRouteWithChildren
  '/speech-check': typeof SpeechCheckRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/assignments': typeof AdminAssignmentsRoute
  '/admin/children': typeof AdminChildrenRouteWithChildren
  '/admin/content': typeof AdminContentRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/diagnostics': typeof AdminDiagnosticsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/parents': typeof AdminParentsRoute
  '/admin/specialists': typeof AdminSpecialistsRoute
  '/settings/children': typeof SettingsChildrenRoute
  '/settings/language': typeof SettingsLanguageRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/specialist/$id': typeof SpecialistIdRoute
  '/admin': typeof AdminIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/admin/children/$id': typeof AdminChildrenIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-child': typeof AddChildRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/exercises': typeof ExercisesRoute
  '/games': typeof GamesRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRouteWithChildren
  '/specialist': typeof SpecialistRouteWithChildren
  '/speech-check': typeof SpeechCheckRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/assignments': typeof AdminAssignmentsRoute
  '/admin/children': typeof AdminChildrenRouteWithChildren
  '/admin/content': typeof AdminContentRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/diagnostics': typeof AdminDiagnosticsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/parents': typeof AdminParentsRoute
  '/admin/specialists': typeof AdminSpecialistsRoute
  '/settings/children': typeof SettingsChildrenRoute
  '/settings/language': typeof SettingsLanguageRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/specialist/$id': typeof SpecialistIdRoute
  '/admin/': typeof AdminIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/admin/children/$id': typeof AdminChildrenIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-child'
    | '/auth'
    | '/chat'
    | '/dashboard'
    | '/diagnostics'
    | '/exercises'
    | '/games'
    | '/notifications'
    | '/onboarding'
    | '/progress'
    | '/settings'
    | '/specialist'
    | '/speech-check'
    | '/admin/analytics'
    | '/admin/assignments'
    | '/admin/children'
    | '/admin/content'
    | '/admin/dashboard'
    | '/admin/diagnostics'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/parents'
    | '/admin/specialists'
    | '/settings/children'
    | '/settings/language'
    | '/settings/notifications'
    | '/settings/profile'
    | '/specialist/$id'
    | '/admin/'
    | '/settings/'
    | '/admin/children/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-child'
    | '/auth'
    | '/chat'
    | '/dashboard'
    | '/diagnostics'
    | '/exercises'
    | '/games'
    | '/notifications'
    | '/onboarding'
    | '/progress'
    | '/specialist'
    | '/speech-check'
    | '/admin/analytics'
    | '/admin/assignments'
    | '/admin/children'
    | '/admin/content'
    | '/admin/dashboard'
    | '/admin/diagnostics'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/parents'
    | '/admin/specialists'
    | '/settings/children'
    | '/settings/language'
    | '/settings/notifications'
    | '/settings/profile'
    | '/specialist/$id'
    | '/admin'
    | '/settings'
    | '/admin/children/$id'
  id:
    | '__root__'
    | '/'
    | '/add-child'
    | '/auth'
    | '/chat'
    | '/dashboard'
    | '/diagnostics'
    | '/exercises'
    | '/games'
    | '/notifications'
    | '/onboarding'
    | '/progress'
    | '/settings'
    | '/specialist'
    | '/speech-check'
    | '/admin/analytics'
    | '/admin/assignments'
    | '/admin/children'
    | '/admin/content'
    | '/admin/dashboard'
    | '/admin/diagnostics'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/parents'
    | '/admin/specialists'
    | '/settings/children'
    | '/settings/language'
    | '/settings/notifications'
    | '/settings/profile'
    | '/specialist/$id'
    | '/admin/'
    | '/settings/'
    | '/admin/children/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddChildRoute: typeof AddChildRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  ExercisesRoute: typeof ExercisesRoute
  GamesRoute: typeof GamesRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  ProgressRoute: typeof ProgressRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SpecialistRoute: typeof SpecialistRouteWithChildren
  SpeechCheckRoute: typeof SpeechCheckRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAssignmentsRoute: typeof AdminAssignmentsRoute
  AdminChildrenRoute: typeof AdminChildrenRouteWithChildren
  AdminContentRoute: typeof AdminContentRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDiagnosticsRoute: typeof AdminDiagnosticsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminParentsRoute: typeof AdminParentsRoute
  AdminSpecialistsRoute: typeof AdminSpecialistsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/speech-check': {
      id: '/speech-check'
      path: '/speech-check'
      fullPath: '/speech-check'
      preLoaderRoute: typeof SpeechCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialist': {
      id: '/specialist'
      path: '/specialist'
      fullPath: '/specialist'
      preLoaderRoute: typeof SpecialistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises': {
      id: '/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof ExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-child': {
      id: '/add-child'
      path: '/add-child'
      fullPath: '/add-child'
      preLoaderRoute: typeof AddChildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialist/$id': {
      id: '/specialist/$id'
      path: '/$id'
      fullPath: '/specialist/$id'
      preLoaderRoute: typeof SpecialistIdRouteImport
      parentRoute: typeof SpecialistRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/language': {
      id: '/settings/language'
      path: '/language'
      fullPath: '/settings/language'
      preLoaderRoute: typeof SettingsLanguageRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/children': {
      id: '/settings/children'
      path: '/children'
      fullPath: '/settings/children'
      preLoaderRoute: typeof SettingsChildrenRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/admin/specialists': {
      id: '/admin/specialists'
      path: '/admin/specialists'
      fullPath: '/admin/specialists'
      preLoaderRoute: typeof AdminSpecialistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/parents': {
      id: '/admin/parents'
      path: '/admin/parents'
      fullPath: '/admin/parents'
      preLoaderRoute: typeof AdminParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/diagnostics': {
      id: '/admin/diagnostics'
      path: '/admin/diagnostics'
      fullPath: '/admin/diagnostics'
      preLoaderRoute: typeof AdminDiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/children': {
      id: '/admin/children'
      path: '/admin/children'
      fullPath: '/admin/children'
      preLoaderRoute: typeof AdminChildrenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/assignments': {
      id: '/admin/assignments'
      path: '/admin/assignments'
      fullPath: '/admin/assignments'
      preLoaderRoute: typeof AdminAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/children/$id': {
      id: '/admin/children/$id'
      path: '/$id'
      fullPath: '/admin/children/$id'
      preLoaderRoute: typeof AdminChildrenIdRouteImport
      parentRoute: typeof AdminChildrenRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsChildrenRoute: typeof SettingsChildrenRoute
  SettingsLanguageRoute: typeof SettingsLanguageRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsChildrenRoute: SettingsChildrenRoute,
  SettingsLanguageRoute: SettingsLanguageRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface SpecialistRouteChildren {
  SpecialistIdRoute: typeof SpecialistIdRoute
}

const SpecialistRouteChildren: SpecialistRouteChildren = {
  SpecialistIdRoute: SpecialistIdRoute,
}

const SpecialistRouteWithChildren = SpecialistRoute._addFileChildren(
  SpecialistRouteChildren,
)

interface AdminChildrenRouteChildren {
  AdminChildrenIdRoute: typeof AdminChildrenIdRoute
}

const AdminChildrenRouteChildren: AdminChildrenRouteChildren = {
  AdminChildrenIdRoute: AdminChildrenIdRoute,
}

const AdminChildrenRouteWithChildren = AdminChildrenRoute._addFileChildren(
  AdminChildrenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddChildRoute: AddChildRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  ExercisesRoute: ExercisesRoute,
  GamesRoute: GamesRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  ProgressRoute: ProgressRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SpecialistRoute: SpecialistRouteWithChildren,
  SpeechCheckRoute: SpeechCheckRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAssignmentsRoute: AdminAssignmentsRoute,
  AdminChildrenRoute: AdminChildrenRouteWithChildren,
  AdminContentRoute: AdminContentRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDiagnosticsRoute: AdminDiagnosticsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminParentsRoute: AdminParentsRoute,
  AdminSpecialistsRoute: AdminSpecialistsRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
