/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpeechCheckRouteImport } from './routes/speech-check'
import { Route as SpecialistRouteImport } from './routes/specialist'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as GamesRouteImport } from './routes/games'
import { Route as ExercisesRouteImport } from './routes/exercises'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AddChildRouteImport } from './routes/add-child'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarjaIndexRouteImport } from './routes/marja.index'
import { Route as SpecialistIdRouteImport } from './routes/specialist.$id'
import { Route as MarjaServicesRouteImport } from './routes/marja.services'
import { Route as MarjaProfileRouteImport } from './routes/marja.profile'
import { Route as MarjaOrdersRouteImport } from './routes/marja.orders'
import { Route as MarjaOrderSuccessRouteImport } from './routes/marja.order-success'
import { Route as MarjaMarketRouteImport } from './routes/marja.market'
import { Route as MarjaCoursesRouteImport } from './routes/marja.courses'
import { Route as MarjaCheckoutRouteImport } from './routes/marja.checkout'
import { Route as MarjaCartRouteImport } from './routes/marja.cart'
import { Route as MarjaProductIdRouteImport } from './routes/marja.product.$id'

const SpeechCheckRoute = SpeechCheckRouteImport.update({
  id: '/speech-check',
  path: '/speech-check',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialistRoute = SpecialistRouteImport.update({
  id: '/specialist',
  path: '/specialist',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesRoute = ExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AddChildRoute = AddChildRouteImport.update({
  id: '/add-child',
  path: '/add-child',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarjaIndexRoute = MarjaIndexRouteImport.update({
  id: '/marja/',
  path: '/marja/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialistIdRoute = SpecialistIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SpecialistRoute,
} as any)
const MarjaServicesRoute = MarjaServicesRouteImport.update({
  id: '/marja/services',
  path: '/marja/services',
  getParentRoute: () => rootRouteImport,
} as any)
const MarjaProfileRoute = MarjaProfileRouteImport.update({
  id: '/marja/profile',
  path: '/marja/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MarjaOrdersRoute = MarjaOrdersRouteImport.update({
  id: '/marja/orders',
  path: '/marja/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MarjaOrderSuccessRoute = MarjaOrderSuccessRouteImport.update({
  id: '/marja/order-success',
  path: '/marja/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const MarjaMarketRoute = MarjaMarketRouteImport.update({
  id: '/marja/market',
  path: '/marja/market',
  getParentRoute: () => rootRouteImport,
} as any)
const MarjaCoursesRoute = MarjaCoursesRouteImport.update({
  id: '/marja/courses',
  path: '/marja/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const MarjaCheckoutRoute = MarjaCheckoutRouteImport.update({
  id: '/marja/checkout',
  path: '/marja/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const MarjaCartRoute = MarjaCartRouteImport.update({
  id: '/marja/cart',
  path: '/marja/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const MarjaProductIdRoute = MarjaProductIdRouteImport.update({
  id: '/marja/product/$id',
  path: '/marja/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-child': typeof AddChildRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/exercises': typeof ExercisesRoute
  '/games': typeof GamesRoute
  '/onboarding': typeof OnboardingRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/specialist': typeof SpecialistRouteWithChildren
  '/speech-check': typeof SpeechCheckRoute
  '/marja/cart': typeof MarjaCartRoute
  '/marja/checkout': typeof MarjaCheckoutRoute
  '/marja/courses': typeof MarjaCoursesRoute
  '/marja/market': typeof MarjaMarketRoute
  '/marja/order-success': typeof MarjaOrderSuccessRoute
  '/marja/orders': typeof MarjaOrdersRoute
  '/marja/profile': typeof MarjaProfileRoute
  '/marja/services': typeof MarjaServicesRoute
  '/specialist/$id': typeof SpecialistIdRoute
  '/marja/': typeof MarjaIndexRoute
  '/marja/product/$id': typeof MarjaProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-child': typeof AddChildRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/exercises': typeof ExercisesRoute
  '/games': typeof GamesRoute
  '/onboarding': typeof OnboardingRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/specialist': typeof SpecialistRouteWithChildren
  '/speech-check': typeof SpeechCheckRoute
  '/marja/cart': typeof MarjaCartRoute
  '/marja/checkout': typeof MarjaCheckoutRoute
  '/marja/courses': typeof MarjaCoursesRoute
  '/marja/market': typeof MarjaMarketRoute
  '/marja/order-success': typeof MarjaOrderSuccessRoute
  '/marja/orders': typeof MarjaOrdersRoute
  '/marja/profile': typeof MarjaProfileRoute
  '/marja/services': typeof MarjaServicesRoute
  '/specialist/$id': typeof SpecialistIdRoute
  '/marja': typeof MarjaIndexRoute
  '/marja/product/$id': typeof MarjaProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-child': typeof AddChildRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/exercises': typeof ExercisesRoute
  '/games': typeof GamesRoute
  '/onboarding': typeof OnboardingRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/specialist': typeof SpecialistRouteWithChildren
  '/speech-check': typeof SpeechCheckRoute
  '/marja/cart': typeof MarjaCartRoute
  '/marja/checkout': typeof MarjaCheckoutRoute
  '/marja/courses': typeof MarjaCoursesRoute
  '/marja/market': typeof MarjaMarketRoute
  '/marja/order-success': typeof MarjaOrderSuccessRoute
  '/marja/orders': typeof MarjaOrdersRoute
  '/marja/profile': typeof MarjaProfileRoute
  '/marja/services': typeof MarjaServicesRoute
  '/specialist/$id': typeof SpecialistIdRoute
  '/marja/': typeof MarjaIndexRoute
  '/marja/product/$id': typeof MarjaProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-child'
    | '/auth'
    | '/chat'
    | '/dashboard'
    | '/diagnostics'
    | '/exercises'
    | '/games'
    | '/onboarding'
    | '/progress'
    | '/settings'
    | '/specialist'
    | '/speech-check'
    | '/marja/cart'
    | '/marja/checkout'
    | '/marja/courses'
    | '/marja/market'
    | '/marja/order-success'
    | '/marja/orders'
    | '/marja/profile'
    | '/marja/services'
    | '/specialist/$id'
    | '/marja/'
    | '/marja/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-child'
    | '/auth'
    | '/chat'
    | '/dashboard'
    | '/diagnostics'
    | '/exercises'
    | '/games'
    | '/onboarding'
    | '/progress'
    | '/settings'
    | '/specialist'
    | '/speech-check'
    | '/marja/cart'
    | '/marja/checkout'
    | '/marja/courses'
    | '/marja/market'
    | '/marja/order-success'
    | '/marja/orders'
    | '/marja/profile'
    | '/marja/services'
    | '/specialist/$id'
    | '/marja'
    | '/marja/product/$id'
  id:
    | '__root__'
    | '/'
    | '/add-child'
    | '/auth'
    | '/chat'
    | '/dashboard'
    | '/diagnostics'
    | '/exercises'
    | '/games'
    | '/onboarding'
    | '/progress'
    | '/settings'
    | '/specialist'
    | '/speech-check'
    | '/marja/cart'
    | '/marja/checkout'
    | '/marja/courses'
    | '/marja/market'
    | '/marja/order-success'
    | '/marja/orders'
    | '/marja/profile'
    | '/marja/services'
    | '/specialist/$id'
    | '/marja/'
    | '/marja/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddChildRoute: typeof AddChildRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  ExercisesRoute: typeof ExercisesRoute
  GamesRoute: typeof GamesRoute
  OnboardingRoute: typeof OnboardingRoute
  ProgressRoute: typeof ProgressRoute
  SettingsRoute: typeof SettingsRoute
  SpecialistRoute: typeof SpecialistRouteWithChildren
  SpeechCheckRoute: typeof SpeechCheckRoute
  MarjaCartRoute: typeof MarjaCartRoute
  MarjaCheckoutRoute: typeof MarjaCheckoutRoute
  MarjaCoursesRoute: typeof MarjaCoursesRoute
  MarjaMarketRoute: typeof MarjaMarketRoute
  MarjaOrderSuccessRoute: typeof MarjaOrderSuccessRoute
  MarjaOrdersRoute: typeof MarjaOrdersRoute
  MarjaProfileRoute: typeof MarjaProfileRoute
  MarjaServicesRoute: typeof MarjaServicesRoute
  MarjaIndexRoute: typeof MarjaIndexRoute
  MarjaProductIdRoute: typeof MarjaProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/speech-check': {
      id: '/speech-check'
      path: '/speech-check'
      fullPath: '/speech-check'
      preLoaderRoute: typeof SpeechCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialist': {
      id: '/specialist'
      path: '/specialist'
      fullPath: '/specialist'
      preLoaderRoute: typeof SpecialistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises': {
      id: '/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof ExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-child': {
      id: '/add-child'
      path: '/add-child'
      fullPath: '/add-child'
      preLoaderRoute: typeof AddChildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marja/': {
      id: '/marja/'
      path: '/marja'
      fullPath: '/marja/'
      preLoaderRoute: typeof MarjaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialist/$id': {
      id: '/specialist/$id'
      path: '/$id'
      fullPath: '/specialist/$id'
      preLoaderRoute: typeof SpecialistIdRouteImport
      parentRoute: typeof SpecialistRoute
    }
    '/marja/services': {
      id: '/marja/services'
      path: '/marja/services'
      fullPath: '/marja/services'
      preLoaderRoute: typeof MarjaServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marja/profile': {
      id: '/marja/profile'
      path: '/marja/profile'
      fullPath: '/marja/profile'
      preLoaderRoute: typeof MarjaProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marja/orders': {
      id: '/marja/orders'
      path: '/marja/orders'
      fullPath: '/marja/orders'
      preLoaderRoute: typeof MarjaOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marja/order-success': {
      id: '/marja/order-success'
      path: '/marja/order-success'
      fullPath: '/marja/order-success'
      preLoaderRoute: typeof MarjaOrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marja/market': {
      id: '/marja/market'
      path: '/marja/market'
      fullPath: '/marja/market'
      preLoaderRoute: typeof MarjaMarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marja/courses': {
      id: '/marja/courses'
      path: '/marja/courses'
      fullPath: '/marja/courses'
      preLoaderRoute: typeof MarjaCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marja/checkout': {
      id: '/marja/checkout'
      path: '/marja/checkout'
      fullPath: '/marja/checkout'
      preLoaderRoute: typeof MarjaCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marja/cart': {
      id: '/marja/cart'
      path: '/marja/cart'
      fullPath: '/marja/cart'
      preLoaderRoute: typeof MarjaCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marja/product/$id': {
      id: '/marja/product/$id'
      path: '/marja/product/$id'
      fullPath: '/marja/product/$id'
      preLoaderRoute: typeof MarjaProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SpecialistRouteChildren {
  SpecialistIdRoute: typeof SpecialistIdRoute
}

const SpecialistRouteChildren: SpecialistRouteChildren = {
  SpecialistIdRoute: SpecialistIdRoute,
}

const SpecialistRouteWithChildren = SpecialistRoute._addFileChildren(
  SpecialistRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddChildRoute: AddChildRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  ExercisesRoute: ExercisesRoute,
  GamesRoute: GamesRoute,
  OnboardingRoute: OnboardingRoute,
  ProgressRoute: ProgressRoute,
  SettingsRoute: SettingsRoute,
  SpecialistRoute: SpecialistRouteWithChildren,
  SpeechCheckRoute: SpeechCheckRoute,
  MarjaCartRoute: MarjaCartRoute,
  MarjaCheckoutRoute: MarjaCheckoutRoute,
  MarjaCoursesRoute: MarjaCoursesRoute,
  MarjaMarketRoute: MarjaMarketRoute,
  MarjaOrderSuccessRoute: MarjaOrderSuccessRoute,
  MarjaOrdersRoute: MarjaOrdersRoute,
  MarjaProfileRoute: MarjaProfileRoute,
  MarjaServicesRoute: MarjaServicesRoute,
  MarjaIndexRoute: MarjaIndexRoute,
  MarjaProductIdRoute: MarjaProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
