/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpeechCheckRouteImport } from './routes/speech-check'
import { Route as SpecialistRouteImport } from './routes/specialist'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as GamesRouteImport } from './routes/games'
import { Route as ExercisesRouteImport } from './routes/exercises'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AddChildRouteImport } from './routes/add-child'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpecialistIdRouteImport } from './routes/specialist.$id'

const SpeechCheckRoute = SpeechCheckRouteImport.update({
  id: '/speech-check',
  path: '/speech-check',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialistRoute = SpecialistRouteImport.update({
  id: '/specialist',
  path: '/specialist',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesRoute = ExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AddChildRoute = AddChildRouteImport.update({
  id: '/add-child',
  path: '/add-child',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialistIdRoute = SpecialistIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SpecialistRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-child': typeof AddChildRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/exercises': typeof ExercisesRoute
  '/games': typeof GamesRoute
  '/onboarding': typeof OnboardingRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/specialist': typeof SpecialistRouteWithChildren
  '/speech-check': typeof SpeechCheckRoute
  '/specialist/$id': typeof SpecialistIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-child': typeof AddChildRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/exercises': typeof ExercisesRoute
  '/games': typeof GamesRoute
  '/onboarding': typeof OnboardingRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/specialist': typeof SpecialistRouteWithChildren
  '/speech-check': typeof SpeechCheckRoute
  '/specialist/$id': typeof SpecialistIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-child': typeof AddChildRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/exercises': typeof ExercisesRoute
  '/games': typeof GamesRoute
  '/onboarding': typeof OnboardingRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/specialist': typeof SpecialistRouteWithChildren
  '/speech-check': typeof SpeechCheckRoute
  '/specialist/$id': typeof SpecialistIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-child'
    | '/auth'
    | '/chat'
    | '/dashboard'
    | '/diagnostics'
    | '/exercises'
    | '/games'
    | '/onboarding'
    | '/progress'
    | '/settings'
    | '/specialist'
    | '/speech-check'
    | '/specialist/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-child'
    | '/auth'
    | '/chat'
    | '/dashboard'
    | '/diagnostics'
    | '/exercises'
    | '/games'
    | '/onboarding'
    | '/progress'
    | '/settings'
    | '/specialist'
    | '/speech-check'
    | '/specialist/$id'
  id:
    | '__root__'
    | '/'
    | '/add-child'
    | '/auth'
    | '/chat'
    | '/dashboard'
    | '/diagnostics'
    | '/exercises'
    | '/games'
    | '/onboarding'
    | '/progress'
    | '/settings'
    | '/specialist'
    | '/speech-check'
    | '/specialist/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddChildRoute: typeof AddChildRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  ExercisesRoute: typeof ExercisesRoute
  GamesRoute: typeof GamesRoute
  OnboardingRoute: typeof OnboardingRoute
  ProgressRoute: typeof ProgressRoute
  SettingsRoute: typeof SettingsRoute
  SpecialistRoute: typeof SpecialistRouteWithChildren
  SpeechCheckRoute: typeof SpeechCheckRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/speech-check': {
      id: '/speech-check'
      path: '/speech-check'
      fullPath: '/speech-check'
      preLoaderRoute: typeof SpeechCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialist': {
      id: '/specialist'
      path: '/specialist'
      fullPath: '/specialist'
      preLoaderRoute: typeof SpecialistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises': {
      id: '/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof ExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-child': {
      id: '/add-child'
      path: '/add-child'
      fullPath: '/add-child'
      preLoaderRoute: typeof AddChildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialist/$id': {
      id: '/specialist/$id'
      path: '/$id'
      fullPath: '/specialist/$id'
      preLoaderRoute: typeof SpecialistIdRouteImport
      parentRoute: typeof SpecialistRoute
    }
  }
}

interface SpecialistRouteChildren {
  SpecialistIdRoute: typeof SpecialistIdRoute
}

const SpecialistRouteChildren: SpecialistRouteChildren = {
  SpecialistIdRoute: SpecialistIdRoute,
}

const SpecialistRouteWithChildren = SpecialistRoute._addFileChildren(
  SpecialistRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddChildRoute: AddChildRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  ExercisesRoute: ExercisesRoute,
  GamesRoute: GamesRoute,
  OnboardingRoute: OnboardingRoute,
  ProgressRoute: ProgressRoute,
  SettingsRoute: SettingsRoute,
  SpecialistRoute: SpecialistRouteWithChildren,
  SpeechCheckRoute: SpeechCheckRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
